# Generated by Django 5.1 on 2025-02-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybooks',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
