# Generated by Django 5.1 on 2025-02-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_alter_mybooks_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooks',
            name='image',
            field=models.ImageField(default='prog1.jpg', upload_to='media/'),
        ),
    ]
