# Generated by Django 5.1 on 2025-02-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0003_mybooks_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybooks',
            name='image',
        ),
    ]
