# Generated by Django 5.1 on 2025-02-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0004_remove_mybooks_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooks',
            name='image',
            field=models.ImageField(null='Nothing', upload_to='media/'),
            preserve_default='Nothing',
        ),
    ]
